# -*- mode: ruby -*-
# vi: set ft=ruby :

master_ip = "10.11.7.2"
n_node = 4

Vagrant.configure("2") do |config|
  config.vm.box = "k8s-base.box"
  config.vm.box_check_update = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.linked_clone = true
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
mkdir -p /export/kubeadm
swapoff -a
systemctl restart kubelet
sysctl -w net.ipv4.ip_forward=1
SHELL

  config.vm.define "master" do |master|
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
    master.vm.hostname = "master.cluster.tvb-ins.fr"
    master.vm.network "private_network", ip: master_ip
    master.vm.provision "shell", inline: <<-SHELL
kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address=#{master_ip} | tee /var/log/kubeadm-init.log
export KUBECONFIG=/etc/kubernetes/admin.conf 
echo applying network overlay
kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml
kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
grep "kubeadm join" /var/log/kubeadm-init.log > /export/kubeadm/join
cat > /etc/exports <<EOF
/export/kubeadm 10.11.7.0/24(ro)
EOF
systemctl enable --now nfs
# allow vagrant user to cp this file
chmod 660 /etc/kubernetes/admin.conf 
chgrp vagrant /etc/kubernetes/admin.conf 
SHELL
  end

# (1..4).each do |i| puts "#{i}" end
  (1..n_node).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}.cluster.tvb-ins.fr"
      node.vm.network "private_network", ip: "10.11.7.#{10 + i}"
      node.vm.provision "shell", inline: <<-SHELL
echo '#{master_ip}:/export/kubeadm /export/kubeadm nfs bg,ro 0 0' >> /etc/fstab
systemctl enable --now nfs
mount -a
while [[ ! -f /export/kubeadm/join ]]
do
	echo 'waiting for join token to appear!'
	sleep 15
done
. /export/kubeadm/join
SHELL
    end
  end

end
